### ISSUE TITLE
Problem with java versioning.

### ISSUE THREAD

**Issue by RichardB01** [pepijnve/ditaa#13]
Hi,

Trying to use the ditaa with asciidoctor results in an error with Java.

> PS C:\Users\Richa\adprac> asciidoctor -r asciidoctor-diagram test.adoc
> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/asciidoctor/diagram/StdInOutCommandServer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
>         at java.lang.ClassLoader.defineClass1(Native Method)
>         at java.lang.ClassLoader.defineClass(Unknown Source)
>         at java.security.SecureClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.defineClass(Unknown Source)
>         at java.net.URLClassLoader.access$100(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.net.URLClassLoader$1.run(Unknown Source)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
> asciidoctor: ERROR: test.adoc: line 5: Failed to generate image: Error processing request {:url=>"/ditaa", :body=>"┌────────────────┐\n│                │\n│                │\n│                ├──────────────────────┬─────────────────────────────────────────┐\n│                │                      │                                         │\n│                │                      │                                         │\n└───────┬────────┘                      │                                         │\n        │                               │                                         │\n        │                               │                                         │\n        │                               ▼                                         │\n        │                      ┌──────────────────┐                               │\n        │                      │                  │                               │\n        │                      │                  │                               │\n        └─────────────────────►│                  │                               │\n                               │                  │                               │\n                               │                  │                               │\n                               │                  │                               │\n                               │                  │                               │\n                               └──────────────────┘                               │\n                                         ▲                                        │\n                                         │                                        │\n                                         │                                        ▼\n                                         │                             ┌───────────────────┐\n                                         │                             │                   │\n                                         │                             │                   │\n                                         │                             │                   │\n                                         │                             │                   │\n                                         │                             │                   │\n                                         │                             │                   │\n                                         │                             │                   │\n                                         │                             │                   │\n                                         │                             └───────────────────┘\n                                         │\n                                         │\n                                         │\n                                         │\n                                         │\n                                         │\n                                         │", :headers=>{"Accept"=>"image/png", "X-Options"=>""}}
> Encoding of input is UTF-8
> C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/asciidoctor-diagram-2.2.9/lib/asciidoctor-diagram/util/java_socket.rb:34:in `kill': No such process (Errno::ESRCH)
>         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/asciidoctor-diagram-2.2.9/lib/asciidoctor-diagram/util/java_socket.rb:34:in `shutdown'
>         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/asciidoctor-diagram-2.2.9/lib/asciidoctor-diagram/util/java_socket.rb:53:in `block in instance'
> C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/asciidoctor-2.0.20/bin/asciidoctor:16:in `exit': exit (SystemExit)
>         from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/asciidoctor-2.0.20/bin/asciidoctor:16:in `<top (required)>'
>         from C:/Ruby32-x64/bin/asciidoctor:32:in `load'
>         from C:/Ruby32-x64/bin/asciidoctor:32:in `<main>'

Thank you.

**Comment by pepijnve** [comment]
That's expected. A Java 11 or higher runtime is required. You're using a Java 8 runtime.
