### ISSUE TITLE
Remove 'o' as a bullet point pattern

### ISSUE THREAD

**Issue by georgeraraujo** [pepijnve/ditaa#9]
Hi,
Would you consider removing 'o' as a bullet point pattern? 'o' in Portuguese ' is equivalent to the definite article 'the', which results in unintended output:

```
/-------------------------------------------------------------------------------------\
|Coloque um fio de azeite na frigideira.                                              |
|Se quiser, salpique um pouquinho de farinha de trigo – isso ajuda o ovo a não grudar.|
|Deixe aquecer.                                                                       |
\-------------------------------------------------------------------------------------/
      |
      v
/------------------------------------------\
|Quebre o ovo na frigideira.               |
|Salpique uma pitada de sal por todo o ovo.|
\------------------------------------------/
      |
      v
/----------------------------------------------------------------\
|Mantenha em fogo baixo até a clara estar rendada e a gema, mole.|
|Retire o ovo da frigideira e sirva.                             |
\----------------------------------------------------------------/
```

![como_fritar_ovo](https://user-images.githubusercontent.com/4930759/168668458-1c36324f-a5d4-48c5-99a8-81698db245c5.png)

As far as I can tell it would be necessary to change line 817 of `src/main/java/org/stathissideris/ditaa/text/TextGrid.java`:

https://github.com/pepijnve/ditaa/blob/43102eaa6cb5dab1425cb33c7716cf84702a8bc4/src/main/java/org/stathissideris/ditaa/text/TextGrid.java#L813-L822

Thanks!

**Comment by pepijnve** [comment]
Seems like a very reasonable request to me. My only concern is that this may break existing ditaa diagrams.

Also note that this fork of ditaa is only used in asciidoctor-diagram as far as I know. Would this change still be useful for you given that limitation?

**Comment by georgeraraujo** [comment]
I understand your concern about breaking existing diagrams. Should this change be implemented, I think one way of dealing with it would be to include an explanation in the change log stating that users should use ` * ` instead of ` o `.

As for the scope of the change being restricted to asciidoctor-diagram, that's EXACTLY my use case :) I also submitted an issue upstream at https://github.com/stathissideris/ditaa/issues/75 but that project seems inactive. That's why I asked here.

**Comment by pepijnve** [comment]
I think we can retain backwards compatibility and still get you what you need by adding an option. I'm thinking of adding `ditaa-bullet-characters` or something along those lines. The default would be `*o`. In your document you could set this to `*` (or whatever other bullet character you would like to use) to disable the default handling of `o`. Would that work?

**Comment by georgeraraujo** [comment]
It sure would!
